import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#ffffff',
  '--slot4-page-text': '#333334',
  '--slot4-panel-bg': '#f4f8ff',
  '--slot4-surface-bg': '#ffffff',
  '--slot4-muted-text': '#5f5e5e',
  '--slot4-soft-muted-text': '#232222b3',
  '--slot4-accent': '#0e54f1',
  '--slot4-accent-fill': '#0e54f1',
  '--slot4-accent-soft': '#eaf1fe',
  '--slot4-on-accent': '#ffffff',
  '--slot4-dark-bg': '#0a0a0a',
  '--slot4-dark-text': '#ffffff',
  '--slot4-media-bg': '#eaf1fe',
  '--slot4-cream': '#ffffff',
  '--slot4-warm': '#fafcff',
  '--slot4-lavender': '#f4f8ff',
  '--slot4-gray': '#eaf1fe',
  '--slot4-body-gradient': 'none',
  '--editable-page-bg': '#ffffff',
  '--editable-page-text': '#333334',
  '--editable-container': '1620px',
  '--editable-border': '#e5e5e5',
  '--editable-nav-bg': '#ffffff',
  '--editable-nav-text': '#333334',
  '--editable-nav-active': '#0e54f1',
  '--editable-nav-active-text': '#ffffff',
  '--editable-cta-bg': '#0e54f1',
  '--editable-cta-text': '#ffffff',
  '--editable-search-bg': '#ffffff',
  '--editable-footer-bg': '#0a0a0a',
  '--editable-footer-text': '#ffffff',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentSoftText: 'text-[#8db3ff]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/15',
  shadow: 'shadow-[0_12px_40px_rgba(14,84,241,0.08)]',
  shadowStrong: 'shadow-[0_24px_80px_rgba(10,10,10,0.24)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(10,10,10,0.02),rgba(10,10,10,0.84))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-[var(--editable-container)] px-5 sm:px-6 lg:px-[30px]',
    sectionY: 'py-20 sm:py-24 lg:py-[120px]',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-10 lg:grid-cols-[0.9fr_1.1fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[260px] shrink-0 snap-start sm:w-[320px]',
  },
  type: {
    eyebrow: 'editable-label text-xs font-medium uppercase tracking-[0.18em] text-[var(--slot4-accent)]',
    heroTitle: 'text-5xl font-bold leading-[1.05] tracking-[-0.03em] sm:text-6xl lg:text-[5rem]',
    sectionTitle: 'text-3xl font-semibold leading-[1.08] tracking-[-0.02em] sm:text-5xl',
    body: 'text-base leading-[1.7]',
    emphasis: 'editable-accent italic text-[var(--slot4-accent)]',
  },
  surface: {
    card: `rounded-lg border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `rounded-lg border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-lg ${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: 'inline-flex h-14 items-center justify-center gap-2 rounded px-6 text-sm font-semibold text-white transition duration-300 bg-[linear-gradient(180deg,#44c7f6_0%,#0037f0_100%)] hover:brightness-110',
    secondary: 'inline-flex h-14 items-center justify-center gap-2 rounded border border-[var(--editable-border)] bg-white px-6 text-sm font-semibold text-[var(--slot4-page-text)] transition duration-300 hover:border-[var(--slot4-accent)] hover:text-[var(--slot4-accent)]',
    accent: 'inline-flex h-14 items-center justify-center gap-2 rounded bg-[var(--slot4-dark-bg)] px-6 text-sm font-semibold text-white transition duration-300 hover:bg-[var(--slot4-accent)]',
    ghost: 'inline-flex h-14 items-center justify-center gap-2 rounded border border-white/30 bg-white/10 px-6 text-sm font-semibold text-white backdrop-blur transition duration-300 hover:bg-white/20',
  },
  badge: {
    pill: 'inline-flex items-center gap-2 rounded-sm border border-[var(--editable-border)] bg-white px-3 py-2 text-xs font-medium',
    accentPill: 'inline-flex items-center gap-2 rounded-sm border border-[var(--slot4-accent)] bg-[var(--slot4-accent-soft)] px-3 py-2 text-xs font-medium text-[var(--slot4-accent)]',
  },
  media: {
    frame: `relative overflow-hidden rounded-md ${editablePalette.mediaBg}`,
    frameFull: `relative overflow-hidden rounded-lg ${editablePalette.mediaBg}`,
    ratio: 'aspect-[4/3]',
  },
  motion: {
    lift: 'transition duration-300 hover:-translate-y-1 hover:shadow-[0_20px_55px_rgba(10,10,10,0.14)]',
    fade: 'transition duration-300 hover:opacity-80',
    zoom: 'transition duration-500 group-hover:scale-[1.04]',
  },
} as const

export const aiLayoutRules = [
  'Change the full site color palette in editableRootStyle first; all homepage sections consume those CSS variables.',
  'Keep page structure in src/editable/sections/HomeSections.tsx so AI can redesign the whole home experience in one file.',
  'Use the reference rhythm: dark hero/showcase bands, soft white content bands, and 120px section spacing.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const

